server:
  port: 9317

spring:
  application:
    name: zuul-sentinel-server
  cloud:
    sentinel:
      filter:
        enabled: false
# Eureka
eureka:
  instance:
    prefer-ip-address: true    # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
