spring:
  application:
    name: eureka-server

server:
  port: 8762

eureka:
  instance:
    hostname: eureka02          # 主机名，不配置的时候，将根据操作系统的主机名来获取
    prefer-ip-address: true     # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    # ip：port
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/   # 相互注册
