spring:
  application:
    name: order-service

server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true     # 是否使用 ip 地址注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port}    # ip：port
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
